# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dltasolutions.github.io
baseurl: ""
title: DLTA Solutions
email: dltasolutions@outlook.com
author: DLTA Solutions
description: ""
copyright: '&copy; 2017 DLTA Solutions.'
credits: 'Site développé à partir du thème <a href="http://startbootstrap.com/template-overviews/clean-blog/">Clean Blog</a> par <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

collections:
- sections
- equipe

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/dltasolutions 
